- name: demo on filters
  hosts: localhost
  connection: local
  vars:
    topics: Linux, shell, Ansible, Terraform
    tagMap:
      name: Ansible
      project: roboshop
      environment: dev
    tagsList:   [
        {
            "key": "name",
            "value": "Ansible"
        },
        {
            "key": "project",
            "value": "roboshop"
        },
        {
            "key": "environment",
            "value": "dev"
        }
    ]
    full_name: G kiran kumar
    ip_address: 174.90.78.17
  tasks:
  - name: convert string to list
    debug: 
      msg: "Topics are: {{ topics | split(',') }}"

  - name: set default value
    debug:
      msg: "Hi {{ Greeting | default('Good Morning') }}"# greetings is not defined anywhere in the script so if we give default values it take that only, or if we define greeting it will that value only

  - name: convert map to list
    debug:
      msg: "{{ tagMap | dict2items }}"

  - name: convert list to map
    debug:
      msg: "{{ tagsList | items2dict }}"

  - name: convert lowercase to uppercase
    debug:
      msg: "{{ full_name | upper }}"

  - name: check ipv4 address
    debug:
      msg: "{{ ip_address | ansible.utils.ipv4 }}"    #pip3.9 install netaddr this need to be insatlled for working ipv4 filter


