- name: demo on filters
  hosts: localhost
  connection: local
  vars:
    topics: Linux, shell, Ansible, Terraform
  tasks:
  - name: convert string to list
    debug: 
      msg: "Topics are: {{ topics | split(',') }}"

  - name: set default value
    debug:
      msg: "Hi {{ Greeting | default('Good Morning') }}"
      #msg: "Hi {{ Greeting }}"

