- name: demo on error handling
# normally ansible will exit from the execution if it get any error
  hosts: localhost
  connection: local
  tasks:
  - name : check roboshop user exist or not
    command: id roboshop
    register: users_output
    ignore_errors: true

  - name: print user output
    #command: useradd roboshop
    debug:
      msg: "{{ users_output }}"

  - name: create user
    command: useradd roboshop 
    when: users_output.rc != 0  