[frontend]
172.31.33.75 COURSE="Ansible host-1 vars" # this is host level vars for this host alone course var will be passed and other it will be passed host section vars
172.31.30.3 COURSE="Ansible host-2 vars"

[frontendvars]
172.31.33.75 


[catalouge]
172.31.33.75

[user]
172.31.33.75

[cart]
172.31.33.75

# group of groups
[roboshop:children] # if i give roboshop in host section in yaml script it will take all the servers under frontend,catalouge,user,cart
frontend
catalouge
user
cart

[localhost]
localhost

; local group vars
[localhost:vars]
COURSE= "Ansible"
TRAINER= "Kiran"
DURATION= "150hrs"

[frontend:vars]
COURSE= "Ansible"
TRAINER= "Kiran"
DURATION= "150hrs"