[frontend]
98.86.108.107

[catalouge]
98.86.108.107

[user]
98.86.108.107

[cart]
98.86.108.107

[roboshop:children] # if i give roboshop in host section in yaml script it will take all the servers under frontend,catalouge,user,cart
frontend
catalouge
user
cart

